### ISSUE TITLE
What's the problem

### ISSUE THREAD

**Issue by ywj764986639** [MiyukiQAQ/MissAV-Downloader#3]
Traceback (most recent call last):
  File "C:\Users\y\Desktop\MissAV-Downloader-master\downloader.py", line 205, in <module>
    main(url,scp_action=False)
  File "C:\Users\y\Desktop\MissAV-Downloader-master\downloader.py", line 156, in main
    playlist_url = video_m3u8_prefix + movie_uuid + video_playlist_suffix
TypeError: can only concatenate str (not "NoneType") to str

**Comment by MiyukiQAQ** [comment]
your video url please，let me see what's wrong，It's running fine here

**Comment by MiyukiQAQ** [comment]
I like your avatar very much，yes Rei Ayanami
