### ISSUE TITLE
Error using PyCharm

### ISSUE THREAD

**Issue by netoraretrogamer** [MiyukiQAQ/MissAV-Downloader#7]
Hi, I'm getting this error:

Traceback (most recent call last):
  File "Q:\MissAV\downloader.py", line 4, in <module>
    from curl_cffi import requests
ModuleNotFoundError: No module named 'curl_cffi'

**Comment by MiyukiQAQ** [comment]
you need to install the lib，
run "pip install curl_cffi" or "pip3 install curl_cffi" in your cmd

**Comment by MiyukiQAQ** [comment]
You need to use pip to install any libraries you are missing.
If you are prompted 【ModuleNotFoundError: No module named 'abcd'】
then, you need to install abcd.
like this "pip install abcd" (or pip3 install abcd)

**Comment by beef-not** [comment]
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (28) Failed to connect to missav.com port 443 after 21237 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

这个怎么办

**Comment by MiyukiQAQ** [comment]
> curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (28) Failed to connect to missav.com port 443 after 21237 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
> 
> 这个怎么办

http proxy

**Comment by MiyukiQAQ** [comment]
> curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (28) Failed to connect to missav.com port 443 after 21237 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
> 
> 
> 
> 这个怎么办
> 
> 

You need a http proxy server, and then specify your proxy server ip and port in the downloader.py        

Assuming that you use Clash, you can open "allow lan" in Clash, and the default port should be 7890. If your Clash and downloader.py run on the same device, then the proxy server ip is 127.0.0.1

**Comment by beef-not** [comment]
C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\paramiko\pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\paramiko\transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
using proxy enabled
Traceback (most recent call last):
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\requests\session.py", line 984, in request
    c.perform()
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\curl.py", line 292, in perform
    self._check_error(ret, "perform")
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\curl.py", line 137, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (7) Failed to connect to 127.0.0.1 port 7890 after 2028 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\16575\Desktop\MissAV-Downloader-master\downloader.py", line 353, in <module>
    cookie = login_get_cookie(missav_user_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16575\Desktop\MissAV-Downloader-master\downloader.py", line 66, in login_get_cookie
    response = requests.post(url='https://missav.com/api/login', data=missav_user_info, headers=headers,verify=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\requests\__init__.py", line 125, in request
    return s.request(
           ^^^^^^^^^^
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\requests\session.py", line 988, in request
    raise RequestsError(str(e), e.code, rsp) from e
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (7) Failed to connect to 127.0.0.1 port 7890 after 2028 ms: Couldn't connect to server. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

i use nekoray

**Comment by beef-not** [comment]
C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\paramiko\pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
using proxy enabled
C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\paramiko\transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Traceback (most recent call last):
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\requests\session.py", line 984, in request
    c.perform()
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\curl.py", line 292, in perform
    self._check_error(ret, "perform")
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\curl.py", line 137, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Proxy CONNECT aborted. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\16575\Desktop\MissAV-Downloader-master\downloader.py", line 353, in <module>
    cookie = login_get_cookie(missav_user_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16575\Desktop\MissAV-Downloader-master\downloader.py", line 66, in login_get_cookie
    response = requests.post(url='https://missav.com/api/login', data=missav_user_info, headers=headers, verify=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\requests\__init__.py", line 125, in request
    return s.request(
           ^^^^^^^^^^
  File "C:\Users\16575\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\requests\session.py", line 988, in request
    raise RequestsError(str(e), e.code, rsp) from e
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (56) Proxy CONNECT aborted. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

 it's aborted
i didn't see something like allowlan in config

**Comment by MiyukiQAQ** [comment]
> i used nekoray，
> 
> [nekoray.json](https://github.com/user-attachments/files/16611313/nekoray.json)

Show me your contact information, such as QQ ,WeChat or Telegram, and I will help you solve it.

**Comment by beef-not** [comment]
qq：1657548687

**Comment by MiyukiQAQ** [comment]
> qq：1657548687
> 
> 

I added you.
